routes/web.php
<?php
use App\Http\Controllers\HomePageController;
use App\Http\Controllers\quoterequestController;
use App\Http\Controllers\AboutUsController;
use App\Http\Controllers\servicesController;
use App\Http\Controllers\cloudofferingController;
use App\Http\Controllers\citrixproductController;
use App\Http\Controllers\productproductController;
use App\Http\Controllers\customersController;
use App\Http\Controllers\ContactUsController;
use App\Http\Controllers\LocationsController;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

// Route::get('/', function () {
//     return view('welcome');
// })->name('home');
Route::get('/', [HomePageController::class, 'render'])->name('home');

Route::get('/about', [AboutUsController::class, 'first'])->name('about-us');

Route::post('/quoterequest' , [quoterequestController::class, 'request'])->name('quote');

Route::get('/cloudoffering', [cloudofferingController::class, 'second'])->name('offerings');

Route::get('/citrix', [citrixproductController::class, 'third'])->name('product1');

Route::get('/products', [productproductController::class, 'fourth'])->name('product2');

Route::get('/services', [servicesController::class, 'fifth'])->name('service');

Route::get('/services/{id}', [servicesController::class, 'display_services'])->name('service1');

// Route::get('/services/{id}', [HomePageController::class, 'display_services'])->name('service1');

Route::get('/customers', [customersController::class, 'sixth'])->name('customers');

Route::post('/contact' , [ContactUsController::class, 'contact'])->name('contact');


Route::get('/contact' , [LocationsController::class, 'seventh'])->name('contact');

Route::get('/quoterequest', function () {
    return view('quoterequest');
})->name('quote');

// Route::get('/about', function () {
//     return view('about');
// })->name('about-us');

// Route::get('/contact', function () {
//     return view('contact');
// })->name('contact');

// Route::get('/cloudoffering', function () {
//     return view('cloudoffering');
// })->name('offerings');

// Route::get('/citrix', function () {
//     return view('citrix');
// })->name('product1');

// Route::get('/products', function () {
//     return view('products');
// })->name('product2');

// Route::get('/services', function () {
//     return view('services');
// })->name('service');

// Route::get('/customers', function () {
//     return view('customers');
// })->name('customers');

app/Models/bannermodel.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class bannermodel extends Model
{
    use HasFactory;
    protected $table='banner';

    public function getImageAttribute(){
        return env('DATA_URL')."/banner_background/".$this->id.".".$this->extension_background_image."?v=.".$this->version;
    }

}

resources/views/about.blade.php
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <link rel="stylesheet" href="{{ env('APP_URL') }}/css/app.css">
    <title>ABOUT US</title>
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Open+Sans:wght@300;400;500;600;700;800&display=swap"
        rel="stylesheet">
</head>

<body>
<div class="content-fluid">@include('components.bmenu')</div>
    <div class="content-fluid">@include('components.navbarslide')</div>
    @include('components.navbar')

    <section class="aboutus-header">
        <div class="content-fluid">
            <div class="about-bigtitle">
                <span>Home / About Us</span>
                <h1>About Us</h1>
            </div>
            @if (isset($aboutus_video) && count($aboutus_video) > 0)
                @foreach ($aboutus_video as $aboutus_video)
                    {{-- @dd($aboutus_video) --}}
                    <div class="video">
                        <picture>
                            <img class="video-background" src="{{ $aboutus_video->image }}" alt="">

                        </picture>

                    </div>

                    <picture><a href="{{ $aboutus_video['button_link'] }}" target="blank"><img class="playbutton"
                                src="{{ env('APP_URL') }}/images/SVG/play.svg" alt=""></a>
                    </picture>
                @endforeach
            @endif
            <div class="menu-marker"></div>
        </div>

    </section>

    @include('components.aboutus')
    <div class="about-body2">
        <div class="content-fluid">
            @if (isset($informations) && count($informations) > 0)
                @foreach ($informations as $informations)
                    {{-- @dd($informations) --}}
                    @php $g = json_decode($informations ->informations) @endphp
                    {{-- @dd($g) --}}
                    <div class="boxes">
                        @foreach ($g as $informations)
                            @if ($loop->index < 4)
                                <div class="box">
                                    <img src="{{ env('DATA_URL') . $informations->svg }}">
                                    <h2>{{ $informations->title }}</h2>
                                    <p>{!! $informations->description !!}</p>
                                </div>
                            @endif
                        @endforeach
                        {{-- <div class="box">
                            <img src="{{ env('APP_URL') }}/images/SVG/simp.svg" alt="">
                            <h2>SIMPLICITY</h2>
                            <p>No more hassle of acquiring hardware infrastructure, maintenance services or platform
                                updates.
                                All you need to do is have access and log in.</p>
                        </div>
                        <div class="box">
                            <img src="{{ env('APP_URL') }}/images/SVG/tick.svg" alt="">
                            <h2>Security</h2>
                            <p>Cloudtaktiks has a state of the art cyber security and your Data will be protected and
                                hosted by
                                top security measures</p>
                        </div>
                        <div class="box">
                            <img src="{{ env('APP_URL') }}/images/SVG/case.svg" alt="">
                            <h2>ALLOWS YOU TO FOCUS ON THE BUSINESS</h2>
                            <p>With a faster and more efficient cloud platform and services, you can focus on your
                                actual
                                business and revenues</p>
                        </div> --}}
                    </div>
                @endforeach
            @endif
        </div>
    </div>
    @if (isset($description) && count($description) > 0)
        @foreach ($description as $description)
            {{-- @dd($description) --}}
            <div class="about-body3">
                <div class="content-fluid">
                    <div class="text-1">
                        <div class="title">
                            <h1>{{ $description['title'] }}</h1>
                            <p class="p1">
                                {{ $description['sub_title'] }}
                            </p>
                        </div>
                        <div class="p2 ">{!! $description['paragraph'] !!}
                        </div>
                    </div>
                    <picture>
                        <img src="{{ $description->image }}">
                    </picture>
                </div>
            </div>
        @endforeach
    @endif

    <section class="history">
        <div class="content-fluid">
            @if (isset($history) && count($history) > 0)
                @foreach ($history as $history)
                    {{-- @dd($history) --}}
                    @php $i = json_decode($history->details) @endphp
                    {{-- @dd($i) --}}
                    <h1> History</h1>

                    <div class="history-row">

                        @foreach ($i as $history)
                            @if ($loop->iteration % 2 == 0)
                                {{-- @if ($loop->index <= 5) --}}
                                <div class="row1">
                                    <div class="hist"><img src="{{ env('DATA_URL') . $history->image }}"
                                            alt=""></div>
                                    <span class="sp1">{!! $history->paragraph !!}</span>
                                </div>

                                {{-- @endif --}}
                            @else
                                <div class="row1">
                                    <div class="hist"><img src="{{ env('DATA_URL') . $history->image }}"
                                            alt=""></div>
                                    <span class="sp2">{!! $history->paragraph !!}</span>
                                </div>
                            @endif
                        @endforeach


                    </div>
                @endforeach
            @endif

        </div>

    </section>


    <section class="a-end">
        <div class="content-fluid">
            <div class="bigending">
                <h1>
                    Cloudtaktiks is committed to being the <br> trusted cloud partner of SAP Business <br> One users
                    globally

                </h1>
            </div>
        </div>
    </section>
    <script language="javascript" src="/js/require.js?v={{ env('CACHE_VERSION') }}"></script>
    <script language="javascript" src="/js/init.js?v={{ env('CACHE_VERSION') }}"
        attr-cache-version="{{ env('CACHE_VERSION') }}"></script>
<script>const burger = document.querySelector('.burger');
    const navbar = document.querySelector('.navbar');
    const navLink = document.querySelectorAll('.nav-link');

    burger.addEventListener('click', () => {
        navbar.classList.toggle('nav-open');
        burger.classList.toggle('burger-open');
        navLink.forEach(link => {
            link.classList.toggle('nav-link-open');
        })
    });</script>
    @include('components.footer')
</body>

</html>

resources/views/citrix.blade.php
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <link rel="stylesheet" href="{{ env('APP_URL') }}/css/app.css">
    <title>CITRIX|PRODUCT</title>
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Open+Sans:wght@300;400;500;600;700;800&display=swap"
        rel="stylesheet">
</head>

<body>
<div class="content-fluid">@include('components.bmenu')</div>
    @include('components.navbar')

    <div class="citrix-body1">
        <div class="citrix-bigtitle">
            <span>Home / Citrix</span>
            <h1>Our Products</h1>
        </div>
        @if (isset($citrixproduct) && count($citrixproduct) > 0)
            @foreach ($citrixproduct as $citrixproduct)
                <div class="content-fluid">
                    {{-- @dd($citrixproduct) --}}
                    <div class="text-1">
                        <div class="title">
                            <h2>{{ $citrixproduct['title'] }}</h2>

                        </div>
                        <div class="p1">{!! $citrixproduct['paragraph'] !!}
                        </div>
                    </div>
                    <picture>
                        <img src="{{ $citrixproduct->image }}">
                    </picture>
                </div>
            @endforeach
        @endif
    </div>
    <div class="menu-marker"></div>
    <div class="offering-body2">
        <div class="content-fluid">
            @if (isset($citrixcontent) && count($citrixcontent) > 0)
                @foreach ($citrixcontent as $citrixcontent)
                    <div class="boxes">
                        {{-- @dd($citrixcontent) --}}
                        @php $r = json_decode($citrixcontent ->content) @endphp
                        {{-- @dd($r) --}}
                        <div class="box">
                            @foreach ($r as $citrixcontent)
                                @if ($loop->index < 3)
                                    <div class="row">
                                        <img src="{{ env('DATA_URL') . $citrixcontent->svg }}">
                                        <h2>{{ $citrixcontent->details }}</h2>
                                    </div>
                                @endif
                            @endforeach
                            {{-- <div class="row">
                                <img src="{{ env('APP_URL') }}/images/SVG/devices.svg" alt="">
                                <h2>Connect From Any Device</h2>
                            </div>
                            <div class="row">
                                <img src="{{ env('APP_URL') }}/images/SVG/web.svg" alt="">
                                <h2>Web Enable Any Application</h2>
                            </div> --}}
                        </div>
                        <div class="box">
                            @foreach ($r as $citrixcontent)
                                @if ($loop->index > 2)
                                    <div class="row">
                                        <img src="{{ env('DATA_URL') . $citrixcontent->svg }}">
                                        <h2>{{ $citrixcontent->details }}</h2>
                                    </div>
                                @endif
                            @endforeach
                            {{-- <div class="row">
                                <img src="{{ env('APP_URL') }}/images/SVG/webdd.svg" alt="">
                                <h2>Simple To Use</h2>
                            </div>
                            <div class="row">
                                <img src="{{ env('APP_URL') }}/images/SVG/webddd.svg" alt="">
                                <h2>Scalable</h2>
                            </div> --}}
                        </div>
                    </div>
                @endforeach
            @endif
        </div>
    </div>
<script language="javascript" src="/js/require.js?v={{ env('CACHE_VERSION') }}"></script>
<script language="javascript" src="/js/init.js?v={{ env('CACHE_VERSION') }}"
        attr-cache-version="{{ env('CACHE_VERSION') }}"></script>
<script>const burger = document.querySelector('.burger');
    const navbar = document.querySelector('.navbar');
    const navLink = document.querySelectorAll('.nav-link');

    burger.addEventListener('click', () => {
        navbar.classList.toggle('nav-open');
        burger.classList.toggle('burger-open');
        navLink.forEach(link => {
            link.classList.toggle('nav-link-open');
        })
    });</script>

    @include('components.footer')
</body>

</html>

resources/views/customers.blade.php
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <link rel="stylesheet" href="{{ env('APP_URL') }}/css/app.css">
    <title>CUSTOMERS</title>
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Open+Sans:wght@300;400;500;600;700;800&display=swap"
        rel="stylesheet">
</head>

<body>
<div class="content-fluid">@include('components.bmenu')</div>
    <div class="content-fluid">@include('components.navbarslide')</div>
    @include('components.navbar')
    <section class="offers-header">
        <div class="content-fluid">
            <div class="offer-bigtitle">
                <span>Home / Customers</span>
                <h1> Customers</h1>
            </div>

            <picture>
                <img src="{{ env('APP_URL') }}/images/custom.png" alt="">
            </picture>

        </div>
    </section>
    <div class="menu-marker"></div>
    @if (isset($customers) && count($customers) >= 0)
        @foreach ($customers as $customers)
            {{-- @dd($customers) --}}
            <section class="custom-stat">
                <div class="content-fluid">
                    <picture>
                        <img src="{{ $customers->image }}">
                    </picture>
                    <div class="text-1">
                        <div class="title">
                            <h2>{!! $customers['title'] !!}</h2>

                        </div>
                        <div class="p1">{!! $customers['paragraph'] !!}
                            <ul>
                                <li><img src="{{ env('APP_URL') }}/images/SVG/arrow.svg" alt="">300 + SAP B1 Customers
                                </li>
                                <li><img src="{{ env('APP_URL') }}/images/SVG/arrow.svg" alt="">750 + SAP B1 Das</li>
                                <li><img src="{{ env('APP_URL') }}/images/SVG/arrow.svg" alt="">3500 + SAP B1 Cloud
                                    Users</li>
                            </ul>
                        </div>
                    </div>
                </div>
            </section>
        @endforeach
    @endif

    <section class="map">
        <div class="content-fluid">
            <div class="title">
                <h2>Clients locations</h2>

            </div>
            <picture>
                <img src="{{ env('APP_URL') }}/images/map1.png" alt="">
            </picture>
        </div>
    </section>
    @if (isset($stories) && count($stories) >= 0)
        @foreach ($stories as $stories)
            {{-- @dd($stories) --}}
            <section class="stories">
                <div class="content-fluid">
                    <div class="title">
                        <h2>Success Stories</h2>

                    </div>

                    @php $y = json_decode($stories ->content) @endphp
                    {{-- @dd($y) --}}

                    <div class="one">
                        <div class="carousel owl-carousel owl-theme" data-carousel-items="1" data-carousel-autowidth="true"
                             data-carousel-dots="false" loop="flase" data-carousel-loop="true" data-carousel-autoplay="true">
                            @foreach ($y as $stories)
                                @if ($loop->index < 5)
                                    <div class="story">
                                        <picture class="iphone"><img
                                                src="{{ env('DATA_URL') . $stories->iphone }}">
                                        </picture>

                                        <div class="box">
                                            <picture><img src="{{ env('DATA_URL') . $stories->svg }}"></picture>
                                            <p>{!! $stories->paragraph !!}</p>
                                            <div class="d">{!! $stories->details !!}</div>
                                        </div>
                                    </div>
                                @endif
                            @endforeach
                        </div>
                    </div>


                </div>
            </section>
        @endforeach
    @endif
    <script language="javascript" src="/js/require.js?v={{ env('CACHE_VERSION') }}"></script>
    <script language="javascript" src="/js/init.js?v={{ env('CACHE_VERSION') }}"
        attr-cache-version="{{ env('CACHE_VERSION') }}"></script>
<script>const burger = document.querySelector('.burger');
    const navbar = document.querySelector('.navbar');
    const navLink = document.querySelectorAll('.nav-link');

    burger.addEventListener('click', () => {
        navbar.classList.toggle('nav-open');
        burger.classList.toggle('burger-open');
        navLink.forEach(link => {
            link.classList.toggle('nav-link-open');
        })
    });</script>

    @include('components.footer')
</body>


</html>

resources/views/products.blade.php
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <link rel="stylesheet" href="{{ env('APP_URL') }}/css/app.css">
    <title>HOME|PRODUCT</title>
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Open+Sans:wght@300;400;500;600;700;800&display=swap"
        rel="stylesheet">
</head>

<body>
<div class="content-fluid">@include('components.bmenu')</div>
    @include('components.navbar')
    <div class="products-body1">
        <div class="products-bigtitle">
            <span>Home / Our Products</span>
            <h1>Our Products</h1>
        </div>
        <div class="content-fluid">
            @if (isset($productproduct) && count($productproduct) > 0)
                @foreach ($productproduct as $productproduct)
                    {{-- @dd($productproduct) --}}
                    <div class="text-1">
                        <div class="title">
                            <h2>{{ $productproduct['title'] }}</h2>

                        </div>
                        <div class="p1 ">{{ $productproduct['paragraph'] }}
                        </div>
                    </div>
                    <picture>
                        <img src="{{ $productproduct->image }}">
                    </picture>
                @endforeach
            @endif
        </div>
    </div>
    <div class="products-body2">
        <div class="content-fluid">

            <div class="boxes">
                <div class="tit">
                    <h1>Sap business applications</h1>
                </div>
                <div class="box">
                    <div class="row">
                        <img src="{{ env('APP_URL') }}/images/SVG/hana.svg" alt="">
                        <h2>Sap B1 Dedicated for HANA
                        </h2>
                        <div class="divv">
                            <h3>SAP B1 Mobile</h3>
                        </div>
                        <div class="divv">
                            <h3>SAP B1 Sales</h3>
                        </div>
                        {{-- <div class="divv">
                            <h3>Intercompany</h3>
                        </div>
                        <div class="divv">
                            <h3>Integrations apps</h3>
                        </div>
                        <div class="divv">
                            <h3>Intercompany</h3>
                        </div>
                        <div class="divv">
                            <h3>Integrations apps</h3>
                        </div> --}}
                    </div>
                    <div class="row">
                        <img src="{{ env('APP_URL') }}/images/SVG/sql.svg" alt="">
                        <h2>Sap B1 SQL on Cloud</h2>
                        <div class="divv">
                            <h3>SAP B1 Mobile</h3>
                        </div>
                        {{-- <div class="divv">
                            <h3>SAP B1 Sales</h3>
                        </div>
                        <div class="divv">
                            <h3>Intercompany</h3>
                        </div>
                        <div class="divv">
                            <h3>Integrations apps</h3>
                        </div>
                        <div class="divv">
                            <h3>Intercompany</h3>
                        </div>
                        <div class="divv">
                            <h3>Integrations apps</h3>
                        </div> --}}
                    </div>
                    <div class="row">
                        <img src="{{ env('APP_URL') }}/images/SVG/hana.svg" alt="">
                        <h2>Sap B1 Dedicated for HANA<br>
                            and SQL</h2>
                        <div class="divv">
                            <h3>SAP B1 Mobile</h3>
                        </div>
                        <div class="divv">
                            <h3>SAP B1 Sales</h3>
                        </div>
                        <div class="divv">
                            <h3>Intercompany</h3>
                        </div>
                        <div class="divv">
                            <h3>Integrations apps</h3>
                        </div>
                        {{-- <div class="divv">
                            <h3>Intercompany</h3>
                        </div>
                        <div class="divv">
                            <h3>Integrations apps</h3>
                        </div> --}}
                    </div>
                    <div class="row">
                        <img src="{{ env('APP_URL') }}/images/SVG/sql.svg" alt="">
                        <h2>SAP B1 HANA ON CLOUD</h2>
                        <div class="divv">
                            <h3>SAP B1 Mobile</h3>
                        </div>
                        <div class="divv">
                            <h3>SAP B1 Sales</h3>
                        </div>
                        {{-- <div class="divv">
                            <h3>Intercompany</h3>
                        </div>
                        <div class="divv">
                            <h3>Integrations apps</h3>
                        </div>
                        <div class="divv">
                            <h3>Intercompany</h3>
                        </div>
                        <div class="divv">
                            <h3>Integrations apps</h3>
                        </div> --}}
                    </div>

                </div>
            </div>
        </div>
    </div>
    <section class="background" style="background-image:  url('{{ env('APP_URL') }}/images/product-end.png')">
    </section>
    <section class="float">
        <div class="content-fluid">
            <div class="notification">
                <div class="noti-box">
                    <div class="bigtitle">
                        READY TO MOVE YOUR SAP B1 TO CLOUD?
                    </div>
                    <div class="subtitle">Let us plan a hassle free move!</div>
                    <div class="detai">SAP HANA and SAP SQL as low as $29.99 per user per month</div>
                    <div class="try-button">
                        <div class="sub">
                            <a href="">Try it</a>
                        </div>
                    </div>


                </div>

            </div>
        </div>
    </section>



    @include('components.footer')
<script>const burger = document.querySelector('.burger');
    const navbar = document.querySelector('.navbar');
    const navLink = document.querySelectorAll('.nav-link');

    burger.addEventListener('click', () => {
        navbar.classList.toggle('nav-open');
        burger.classList.toggle('burger-open');
        navLink.forEach(link => {
            link.classList.toggle('nav-link-open');
        })
    });</script>
</body>

</html>

resources/views/services.blade.php
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <link rel="stylesheet" href="{{ env('APP_URL') }}/css/app.css">
    <title>HOME|SERVICES</title>
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Open+Sans:wght@300;400;500;600;700;800&display=swap"
        rel="stylesheet">
</head>

<body>
<div class="content-fluid">@include('components.bmenu')</div>
    @include('components.navbar')
    <div class="services-body">
        <div class="services-bigtitle">
            <span>Home / Our Services</span>
            <h1>Our Services</h1>
        </div>

        <div class="menu-marker"></div>
        @if (isset($servicebyid))
            {{-- @dd($servicespage) --}}

                <div class="content-fluid services">
                    <div class="left-col">
                        <picture>
                            <img src="{{ $servicebyid->image }}">
                        </picture>
                    </div>
                    <div class="text-1">
                        <div class="title">
                            <h2>{!! $servicebyid['title'] !!}
                            </h2>

                        </div>
                        <div class="p1 scroll">{!! $servicebyid['paragraph'] !!}
                        </div>
                    </div>

                </div>
             @endif
    </div>

    <section class="switch">
        <div class="content-fluid">
            <div class="options clicked ">
                <div class="link">
                    <div class="carousel owl-carousel owl-theme" data-carousel-items="1" data-carousel-autowidth="true"
                        data-carousel-dots="false" loop="false" data-carousel-loop="true"
                        data-carousel-autoplay="false">

                        @if (isset($servicespage))
                            @foreach ($servicespage as $service)
                                <a href="{{ route('service1', ['id' => $service['id']]) }}">
                                    <div class="option @if($service['id'] == $servicebyid['id']) selected @endif" style="display:block" >
                                        {!! $service['title'] !!}
                                    </div>
                                </a>
                            @endforeach
                        @endif
                    </div>


                </div>
            </div>
        </div>

    </section>




    <script language="javascript" src="/js/require.js?v={{ env('CACHE_VERSION') }}"></script>
    <script language="javascript" src="/js/init.js?v={{ env('CACHE_VERSION') }}"
        attr-cache-version="{{ env('CACHE_VERSION') }}"></script>
    <script>const burger = document.querySelector('.burger');
    const navbar = document.querySelector('.navbar');
    const navLink = document.querySelectorAll('.nav-link');

    burger.addEventListener('click', () => {
        navbar.classList.toggle('nav-open');
        burger.classList.toggle('burger-open');
        navLink.forEach(link => {
            link.classList.toggle('nav-link-open');
        })
    });
    </script>
    @include('components.footer')
</body>

</html>